const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('desktopHost', {
  status: () => ipcRenderer.invoke('host:status'),
  inspectRuntime: (runtimePath) => ipcRenderer.invoke('host:inspect-runtime', runtimePath),
  selectRuntime: () => ipcRenderer.invoke('host:select-runtime'),
  autoDetectRuntime: () => ipcRenderer.invoke('host:auto-detect-runtime'),
  provisionRuntime: () => ipcRenderer.invoke('host:provision-runtime'),
  start: (runtimePath) => ipcRenderer.invoke('host:start', runtimePath),
  stop: () => ipcRenderer.invoke('host:stop'),
  createSafeWorkspace: (name) => ipcRenderer.invoke('host:create-safe-workspace', name),
  selectWorkspace: () => ipcRenderer.invoke('host:select-workspace'),
  workspaceStatus: () => ipcRenderer.invoke('host:workspace-status'),
  openWorkspace: () => ipcRenderer.invoke('host:open-workspace'),
  exportDiagnostics: () => ipcRenderer.invoke('host:export-diagnostics'),
  listModes: () => ipcRenderer.invoke('mode:list'),
  saveMode: (draft) => ipcRenderer.invoke('mode:save', draft),
  deleteMode: (id) => ipcRenderer.invoke('mode:delete', id),
  prepareModeImport: () => ipcRenderer.invoke('mode:prepare-import'),
  commitModeImport: (raw) => ipcRenderer.invoke('mode:commit-import', raw),
  exportMode: (id) => ipcRenderer.invoke('mode:export', id),
  cardSnapshot: () => ipcRenderer.invoke('cards:snapshot'),
  saveCard: (draft) => ipcRenderer.invoke('cards:save', draft),
  deleteCard: (id) => ipcRenderer.invoke('cards:delete', id),
  setActiveCard: (kind, id) => ipcRenderer.invoke('cards:set-active', kind, id),
  prepareCardImport: () => ipcRenderer.invoke('cards:prepare-import'),
  commitCardImport: (raw) => ipcRenderer.invoke('cards:commit-import', raw),
  exportCard: (id) => ipcRenderer.invoke('cards:export', id),
  workbenchSnapshot: () => ipcRenderer.invoke('workbench:snapshot'),
  createTask: (draft) => ipcRenderer.invoke('workbench:create-task', draft),
  createProjectBrief: () => ipcRenderer.invoke('workbench:create-project-brief'),
  retryTask: (id) => ipcRenderer.invoke('workbench:retry-task', id),
  sendMessage: (id, text) => ipcRenderer.invoke('workbench:send-message', id, text),
  cancelTask: (id) => ipcRenderer.invoke('workbench:cancel', id),
  selectTask: (id) => ipcRenderer.invoke('workbench:select-task', id),
  deleteTask: (id) => ipcRenderer.invoke('workbench:delete-task', id),
  handoffPreview: (id) => ipcRenderer.invoke('workbench:handoff-preview', id),
  onSetupProgress: (callback) => ipcRenderer.on('setup:progress', (_event, value) => callback(value)),
  onStatus: (callback) => ipcRenderer.on('host:status', (_event, value) => callback(value))
})
