const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('desktopHost', {
  status: () => ipcRenderer.invoke('host:status'),
  openExternal: (url) => ipcRenderer.invoke('host:open-external', url),
  copyText: (value) => ipcRenderer.invoke('host:copy-text', value),
  modelConnection: () => ipcRenderer.invoke('host:model-connection'),
  saveDeepSeekCredential: (value) => ipcRenderer.invoke('host:save-deepseek-credential', value),
  clearDeepSeekCredential: () => ipcRenderer.invoke('host:clear-deepseek-credential'),
  inspectRuntime: (runtimePath) => ipcRenderer.invoke('host:inspect-runtime', runtimePath),
  selectRuntime: () => ipcRenderer.invoke('host:select-runtime'),
  autoDetectRuntime: () => ipcRenderer.invoke('host:auto-detect-runtime'),
  provisionRuntime: () => ipcRenderer.invoke('host:provision-runtime'),
  start: (runtimePath) => ipcRenderer.invoke('host:start', runtimePath),
  stop: () => ipcRenderer.invoke('host:stop'),
  createSafeWorkspace: (name) => ipcRenderer.invoke('host:create-safe-workspace', name),
  selectWorkspace: () => ipcRenderer.invoke('host:select-workspace'),
  workspaceStatus: () => ipcRenderer.invoke('host:workspace-status'),
  openWorkspace: () => ipcRenderer.invoke('host:open-workspace'),
  exportDiagnostics: () => ipcRenderer.invoke('host:export-diagnostics'),
  ecosystemStatus: () => ipcRenderer.invoke('ecosystem:status'),
  setEcosystemEnabled: (enabled) => ipcRenderer.invoke('ecosystem:set-enabled', enabled),
  refreshEcosystem: () => ipcRenderer.invoke('ecosystem:refresh'),
  controlCenterSnapshot: () => ipcRenderer.invoke('control-center:snapshot'),
  listModes: () => ipcRenderer.invoke('mode:list'),
  saveMode: (draft) => ipcRenderer.invoke('mode:save', draft),
  deleteMode: (id) => ipcRenderer.invoke('mode:delete', id),
  prepareModeImport: () => ipcRenderer.invoke('mode:prepare-import'),
  commitModeImport: (raw) => ipcRenderer.invoke('mode:commit-import', raw),
  exportMode: (id) => ipcRenderer.invoke('mode:export', id),
  cardSnapshot: () => ipcRenderer.invoke('cards:snapshot'),
  saveCard: (draft) => ipcRenderer.invoke('cards:save', draft),
  deleteCard: (id) => ipcRenderer.invoke('cards:delete', id),
  setActiveCard: (kind, id) => ipcRenderer.invoke('cards:set-active', kind, id),
  prepareCardImport: () => ipcRenderer.invoke('cards:prepare-import'),
  commitCardImport: (raw) => ipcRenderer.invoke('cards:commit-import', raw),
  exportCard: (id) => ipcRenderer.invoke('cards:export', id),
  workbenchSnapshot: () => ipcRenderer.invoke('workbench:snapshot'),
  imageDrafts: (scopeId) => ipcRenderer.invoke('workbench:image-drafts', scopeId),
  pickImages: (scopeId) => ipcRenderer.invoke('workbench:pick-images', scopeId),
  removeImage: (scopeId, id) => ipcRenderer.invoke('workbench:remove-image', scopeId, id),
  createTask: (draft) => ipcRenderer.invoke('workbench:create-task', draft),
  createProjectBrief: () => ipcRenderer.invoke('workbench:create-project-brief'),
  createConnectionTest: () => ipcRenderer.invoke('workbench:create-connection-test'),
  retryTask: (id) => ipcRenderer.invoke('workbench:retry-task', id),
  sendMessage: (id, text, attachmentIds) => ipcRenderer.invoke('workbench:send-message', id, text, attachmentIds),
  cancelTask: (id) => ipcRenderer.invoke('workbench:cancel', id),
  respondToInteraction: (id, response) => ipcRenderer.invoke('workbench:respond-interaction', id, response),
  selectTask: (id) => ipcRenderer.invoke('workbench:select-task', id),
  deleteTask: (id) => ipcRenderer.invoke('workbench:delete-task', id),
  handoffPreview: (id) => ipcRenderer.invoke('workbench:handoff-preview', id),
  onSetupProgress: (callback) => ipcRenderer.on('setup:progress', (_event, value) => callback(value)),
  onStatus: (callback) => ipcRenderer.on('host:status', (_event, value) => callback(value))
})
