const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('desktopHost', {
  status: () => ipcRenderer.invoke('host:status'),
  openExternal: (url) => ipcRenderer.invoke('host:open-external', url),
  copyText: (value) => ipcRenderer.invoke('host:copy-text', value),
  modelConnection: () => ipcRenderer.invoke('host:model-connection'),
  modelServicesSnapshot: () => ipcRenderer.invoke('model-services:snapshot'),
  addModelProvider: (provider, value) => ipcRenderer.invoke('host:add-model-provider', { provider, value }),
  saveModelCredential: (ref, value) => ipcRenderer.invoke('host:save-model-credential', ref, value),
  clearModelCredential: (ref) => ipcRenderer.invoke('host:clear-model-credential', ref),
  removeModelProvider: (provider) => ipcRenderer.invoke('host:remove-model-provider', provider),
  inspectRuntime: (runtimePath) => ipcRenderer.invoke('host:inspect-runtime', runtimePath),
  selectRuntime: () => ipcRenderer.invoke('host:select-runtime'),
  autoDetectRuntime: () => ipcRenderer.invoke('host:auto-detect-runtime'),
  provisionRuntime: () => ipcRenderer.invoke('host:provision-runtime'),
  start: (runtimePath) => ipcRenderer.invoke('host:start', runtimePath),
  startManaged: (runtimePath) => ipcRenderer.invoke('host:start-managed', runtimePath),
  confirmSharedEngine: () => ipcRenderer.invoke('host:confirm-shared'),
  stop: () => ipcRenderer.invoke('host:stop'),
  createSafeWorkspace: (name) => ipcRenderer.invoke('host:create-safe-workspace', name),
  selectWorkspace: () => ipcRenderer.invoke('host:select-workspace'),
  workspaceStatus: () => ipcRenderer.invoke('host:workspace-status'),
  useTaskWorkspace: (id) => ipcRenderer.invoke('host:use-task-workspace', id),
  openWorkspace: () => ipcRenderer.invoke('host:open-workspace'),
  exportDiagnostics: () => ipcRenderer.invoke('host:export-diagnostics'),
  ecosystemStatus: () => ipcRenderer.invoke('ecosystem:status'),
  setEcosystemEnabled: (enabled) => ipcRenderer.invoke('ecosystem:set-enabled', enabled),
  refreshEcosystem: () => ipcRenderer.invoke('ecosystem:refresh'),
  controlCenterSnapshot: () => ipcRenderer.invoke('control-center:snapshot'),
  memorySnapshot: () => ipcRenderer.invoke('memory:snapshot'),
  createMemoryCandidate: (input) => ipcRenderer.invoke('memory:create', input),
  reviewMemoryCandidate: (id, status) => ipcRenderer.invoke('memory:review', id, status),
  removeMemory: (id) => ipcRenderer.invoke('memory:remove', id),
  openMemoryFolder: () => ipcRenderer.invoke('memory:open-folder'),
  previewMemoryRetrieval: (query) => ipcRenderer.invoke('memory:preview', query),
  composeMemoryPreview: (query, selectedIds) => ipcRenderer.invoke('memory:compose-preview', { query, selectedIds }),
  workbenchSnapshot: () => ipcRenderer.invoke('workbench:snapshot'),
  modelRoutingCatalog: (id) => ipcRenderer.invoke('workbench:model-catalog', id),
  imageDrafts: (scopeId) => ipcRenderer.invoke('workbench:image-drafts', scopeId),
  pickImages: (scopeId) => ipcRenderer.invoke('workbench:pick-images', scopeId),
  removeImage: (scopeId, id) => ipcRenderer.invoke('workbench:remove-image', scopeId, id),
  createTask: (draft) => ipcRenderer.invoke('workbench:create-task', draft),
  createProjectBrief: () => ipcRenderer.invoke('workbench:create-project-brief'),
  createConnectionTest: (routing) => ipcRenderer.invoke('workbench:create-connection-test', routing),
  retryTask: (id) => ipcRenderer.invoke('workbench:retry-task', id),
  sendMessage: (id, text, attachmentIds, routing) => ipcRenderer.invoke('workbench:send-message', id, text, attachmentIds, routing),
  cancelTask: (id) => ipcRenderer.invoke('workbench:cancel', id),
  respondToInteraction: (id, response) => ipcRenderer.invoke('workbench:respond-interaction', id, response),
  touchInteraction: (id, interactionId) => ipcRenderer.invoke('workbench:touch-interaction', id, interactionId),
  selectTask: (id) => ipcRenderer.invoke('workbench:select-task', id),
  deleteTask: (id) => ipcRenderer.invoke('workbench:delete-task', id),
  handoffPreview: (id) => ipcRenderer.invoke('workbench:handoff-preview', id),
  onSetupProgress: (callback) => ipcRenderer.on('setup:progress', (_event, value) => callback(value)),
  onWorkbenchChanged: (callback) => ipcRenderer.on('workbench:changed', () => callback()),
  onStatus: (callback) => ipcRenderer.on('host:status', (_event, value) => callback(value))
})
